// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PhysicsUIClient is the client API for PhysicsUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PhysicsUIClient interface {
	// ListEngineSpecs returns a list of Physics Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PhysicsUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type physicsUIClient struct {
	cc grpc.ClientConnInterface
}

func NewPhysicsUIClient(cc grpc.ClientConnInterface) PhysicsUIClient {
	return &physicsUIClient{cc}
}

func (c *physicsUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (PhysicsUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &PhysicsUI_ServiceDesc.Streams[0], "/v1.PhysicsUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &physicsUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PhysicsUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type physicsUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *physicsUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *physicsUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.PhysicsUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PhysicsUIServer is the server API for PhysicsUI service.
// All implementations must embed UnimplementedPhysicsUIServer
// for forward compatibility
type PhysicsUIServer interface {
	// ListEngineSpecs returns a list of Physics Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, PhysicsUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedPhysicsUIServer()
}

// UnimplementedPhysicsUIServer must be embedded to have forward compatible implementations.
type UnimplementedPhysicsUIServer struct {
}

func (UnimplementedPhysicsUIServer) ListEngineSpecs(*ListEngineSpecsRequest, PhysicsUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedPhysicsUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedPhysicsUIServer) mustEmbedUnimplementedPhysicsUIServer() {}

// UnsafePhysicsUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PhysicsUIServer will
// result in compilation errors.
type UnsafePhysicsUIServer interface {
	mustEmbedUnimplementedPhysicsUIServer()
}

func RegisterPhysicsUIServer(s grpc.ServiceRegistrar, srv PhysicsUIServer) {
	s.RegisterService(&PhysicsUI_ServiceDesc, srv)
}

func _PhysicsUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PhysicsUIServer).ListEngineSpecs(m, &physicsUIListEngineSpecsServer{stream})
}

type PhysicsUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type physicsUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *physicsUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PhysicsUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PhysicsUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.PhysicsUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PhysicsUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PhysicsUI_ServiceDesc is the grpc.ServiceDesc for PhysicsUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PhysicsUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.PhysicsUI",
	HandlerType: (*PhysicsUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _PhysicsUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _PhysicsUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "physics-ui.proto",
}
